/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hands/l_hand.glb -t -o src/components/astraign/LeftHandModel.tsx 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

interface FingerConfig {
  bend: number;
  spread: number;
  rotation: number;
}
interface HandConfigProps {
  config?: {
    thumb: FingerConfig;
    index: FingerConfig;
    middle: FingerConfig;
    ring: FingerConfig;
    pinky: FingerConfig;
  };
}

type GLTFResult = GLTF & {
  nodes: {
    l_handMeshNode: THREE.SkinnedMesh
    ['pinky-finger-tip']: THREE.Bone
    ['pinky-finger-phalanx-distal']: THREE.Bone
    ['pinky-finger-phalanx-intermediate']: THREE.Bone
    ['pinky-finger-phalanx-proximal']: THREE.Bone
    ['pinky-finger-metacarpal']: THREE.Bone
    ['ring-finger-tip']: THREE.Bone
    ['ring-finger-phalanx-distal']: THREE.Bone
    ['ring-finger-phalanx-intermediate']: THREE.Bone
    ['ring-finger-phalanx-proximal']: THREE.Bone
    ['ring-finger-metacarpal']: THREE.Bone
    ['middle-finger-tip']: THREE.Bone
    ['middle-finger-phalanx-distal']: THREE.Bone
    ['middle-finger-phalanx-intermediate']: THREE.Bone
    ['middle-finger-phalanx-proximal']: THREE.Bone
    ['middle-finger-metacarpal']: THREE.Bone
    ['index-finger-tip']: THREE.Bone
    ['index-finger-phalanx-distal']: THREE.Bone
    ['index-finger-phalanx-intermediate']: THREE.Bone
    ['index-finger-phalanx-proximal']: THREE.Bone
    ['index-finger-metacarpal']: THREE.Bone
    ['thumb-tip']: THREE.Bone
    ['thumb-phalanx-distal']: THREE.Bone
    ['thumb-phalanx-proximal']: THREE.Bone
    ['thumb-metacarpal']: THREE.Bone
    wrist: THREE.Bone
  }
  materials: {
    Default_Material: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function LeftHandModel({ config, ...props }: JSX.IntrinsicElements['group'] & HandConfigProps) {
  const { scene } = useGLTF('/models/hands/l_hand.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone) as GLTFResult

  // Realistic human skin material
  const skinMaterial = React.useMemo(() => {
    return new THREE.MeshPhysicalMaterial({
      color: new THREE.Color('#fcdcc0'), // Natural warm skin tone
      roughness: 0.45,
      metalness: 0.0,
      clearcoat: 0.1,
      clearcoatRoughness: 0.3,
      transmission: 0.05, // Slight subsurface scattering illusion
      thickness: 0.5,
      envMapIntensity: 1.2,
    });
  }, []);

  useFrame(() => {
    if (!config || !nodes) return;

    // Apply finger bends. Typical rigged fingers bend along the Z or X axis depending on rig.
    // For Wonderland Engine hands, bending is usually around Z or X. 
    // We'll map config bend (0=straight, 1=fully bent) to radians (e.g. 0 to Math.PI/2)
    const lerpRate = 0.15;

    // Index
    nodes['index-finger-phalanx-proximal'].rotation.z = THREE.MathUtils.lerp(nodes['index-finger-phalanx-proximal'].rotation.z, config.index.bend * 1.5, lerpRate);
    nodes['index-finger-phalanx-intermediate'].rotation.z = THREE.MathUtils.lerp(nodes['index-finger-phalanx-intermediate'].rotation.z, config.index.bend * 1.5, lerpRate);
    nodes['index-finger-phalanx-distal'].rotation.z = THREE.MathUtils.lerp(nodes['index-finger-phalanx-distal'].rotation.z, config.index.bend * 1.0, lerpRate);
    nodes['index-finger-metacarpal'].rotation.x = THREE.MathUtils.lerp(nodes['index-finger-metacarpal'].rotation.x, (config.index.spread - 0.5) * 0.5, lerpRate);

    // Middle
    nodes['middle-finger-phalanx-proximal'].rotation.z = THREE.MathUtils.lerp(nodes['middle-finger-phalanx-proximal'].rotation.z, config.middle.bend * 1.5, lerpRate);
    nodes['middle-finger-phalanx-intermediate'].rotation.z = THREE.MathUtils.lerp(nodes['middle-finger-phalanx-intermediate'].rotation.z, config.middle.bend * 1.5, lerpRate);
    nodes['middle-finger-phalanx-distal'].rotation.z = THREE.MathUtils.lerp(nodes['middle-finger-phalanx-distal'].rotation.z, config.middle.bend * 1.0, lerpRate);
    nodes['middle-finger-metacarpal'].rotation.x = THREE.MathUtils.lerp(nodes['middle-finger-metacarpal'].rotation.x, (config.middle.spread - 0.5) * 0.5, lerpRate);

    // Ring
    nodes['ring-finger-phalanx-proximal'].rotation.z = THREE.MathUtils.lerp(nodes['ring-finger-phalanx-proximal'].rotation.z, config.ring.bend * 1.5, lerpRate);
    nodes['ring-finger-phalanx-intermediate'].rotation.z = THREE.MathUtils.lerp(nodes['ring-finger-phalanx-intermediate'].rotation.z, config.ring.bend * 1.5, lerpRate);
    nodes['ring-finger-phalanx-distal'].rotation.z = THREE.MathUtils.lerp(nodes['ring-finger-phalanx-distal'].rotation.z, config.ring.bend * 1.0, lerpRate);
    nodes['ring-finger-metacarpal'].rotation.x = THREE.MathUtils.lerp(nodes['ring-finger-metacarpal'].rotation.x, (config.ring.spread - 0.5) * 0.5, lerpRate);

    // Pinky
    nodes['pinky-finger-phalanx-proximal'].rotation.z = THREE.MathUtils.lerp(nodes['pinky-finger-phalanx-proximal'].rotation.z, config.pinky.bend * 1.5, lerpRate);
    nodes['pinky-finger-phalanx-intermediate'].rotation.z = THREE.MathUtils.lerp(nodes['pinky-finger-phalanx-intermediate'].rotation.z, config.pinky.bend * 1.5, lerpRate);
    nodes['pinky-finger-phalanx-distal'].rotation.z = THREE.MathUtils.lerp(nodes['pinky-finger-phalanx-distal'].rotation.z, config.pinky.bend * 1.0, lerpRate);
    nodes['pinky-finger-metacarpal'].rotation.x = THREE.MathUtils.lerp(nodes['pinky-finger-metacarpal'].rotation.x, (config.pinky.spread - 0.5) * 0.5, lerpRate);

    // Thumb
    nodes['thumb-phalanx-proximal'].rotation.z = THREE.MathUtils.lerp(nodes['thumb-phalanx-proximal'].rotation.z, config.thumb.bend * 1.0, lerpRate);
    nodes['thumb-phalanx-distal'].rotation.z = THREE.MathUtils.lerp(nodes['thumb-phalanx-distal'].rotation.z, config.thumb.bend * 1.0, lerpRate);
    nodes['thumb-metacarpal'].rotation.x = THREE.MathUtils.lerp(nodes['thumb-metacarpal'].rotation.x, (config.thumb.spread - 0.5) * 0.8, lerpRate);
    nodes['thumb-metacarpal'].rotation.y = THREE.MathUtils.lerp(nodes['thumb-metacarpal'].rotation.y, (config.thumb.rotation - 0.5) * 1.0, lerpRate);
  });

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes['pinky-finger-tip']} />
      <primitive object={nodes['pinky-finger-phalanx-distal']} />
      <primitive object={nodes['pinky-finger-phalanx-intermediate']} />
      <primitive object={nodes['pinky-finger-phalanx-proximal']} />
      <primitive object={nodes['pinky-finger-metacarpal']} />
      <primitive object={nodes['ring-finger-tip']} />
      <primitive object={nodes['ring-finger-phalanx-distal']} />
      <primitive object={nodes['ring-finger-phalanx-intermediate']} />
      <primitive object={nodes['ring-finger-phalanx-proximal']} />
      <primitive object={nodes['ring-finger-metacarpal']} />
      <primitive object={nodes['middle-finger-tip']} />
      <primitive object={nodes['middle-finger-phalanx-distal']} />
      <primitive object={nodes['middle-finger-phalanx-intermediate']} />
      <primitive object={nodes['middle-finger-phalanx-proximal']} />
      <primitive object={nodes['middle-finger-metacarpal']} />
      <primitive object={nodes['index-finger-tip']} />
      <primitive object={nodes['index-finger-phalanx-distal']} />
      <primitive object={nodes['index-finger-phalanx-intermediate']} />
      <primitive object={nodes['index-finger-phalanx-proximal']} />
      <primitive object={nodes['index-finger-metacarpal']} />
      <primitive object={nodes['thumb-tip']} />
      <primitive object={nodes['thumb-phalanx-distal']} />
      <primitive object={nodes['thumb-phalanx-proximal']} />
      <primitive object={nodes['thumb-metacarpal']} />
      <primitive object={nodes.wrist} />
      <skinnedMesh geometry={nodes.l_handMeshNode.geometry} material={skinMaterial} skeleton={nodes.l_handMeshNode.skeleton} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('/models/hands/l_hand.glb')
