import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import { ArrowLeft, Settings, Play, Pause, ToggleLeft, ToggleRight, Volume2 } from "lucide-react";
import { useAccessibility } from "@/accessibility/AccessibilityProvider";
import HandTracker from "@/components/astraign/HandTracker";
import { useFastSignPipeline } from "@/hooks/useFastSignPipeline";
import { fetchSpeechUrl } from "@/services/api";
import type { Landmark } from "@/hooks/useHandTracking";

interface Props {
  onBack?: () => void;
  onSettings?: () => void;
  focusMode?: boolean;
  embedded?: boolean;
  onStatusChange?: (status: "ready" | "listening" | "processing") => void;
  onAddToHistory?: (audioText: string, aslTranslation: string) => void;
}

const QUICK_PHRASES = [
  "I need help",
  "Please repeat that",
  "Thank you",
  "I understand",
  "Call 911",
  "One moment",
];

const HandLandmark = ({ x, y }: { x: number; y: number }) => (
  <div
    className="absolute w-2.5 h-2.5 rounded-full border border-primary animate-pulse"
    style={{
      left: `${x}%`,
      top: `${y}%`,
      background: "hsl(var(--primary) / 0.4)",
      transform: "translate(-50%, -50%)",
    }}
  />
);

const WaveformBar = ({ i }: { i: number }) => {
  const [h, setH] = useState(Math.random() * 20 + 4);
  useEffect(() => {
    const interval = setInterval(() => setH(Math.random() * 28 + 4), 150 + i * 30);
    return () => clearInterval(interval);
  }, [i]);
  return (
    <div
      className="w-1 rounded-full transition-all duration-150"
      style={{
        height: `${h}px`,
        background: "linear-gradient(to top, hsl(272 76% 53%), hsl(183 100% 50%))",
      }}
    />
  );
};

const POSE_HOLD_MS = 500;
const COOLDOWN_MS = 1800;

export default function SignToVoice({ onBack, onSettings, focusMode: focusModeProp, embedded, onStatusChange, onAddToHistory }: Props) {
  const { settings } = useAccessibility();
  const focusMode = focusModeProp ?? settings.focusMode;
  const [isRecording, setIsRecording] = useState(false);
  const [liveMode, setLiveMode] = useState(true);
  const [translation, setTranslation] = useState("");
  const [manualText, setManualText] = useState("");
  const [confidence, setConfidence] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isSpeakingManual, setIsSpeakingManual] = useState(false);
  const [showParticles, setShowParticles] = useState(false);
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);
  const lastGestureRef = useRef<string>("");
  const lastGestureTimeRef = useRef<number>(0);
  const lastSpokenWordRef = useRef<string>("");
  const lastSpokenTimeRef = useRef<number>(0);

  const speechRate = useMemo(() => {
    const v = Number(getComputedStyle(document.documentElement).getPropertyValue("--a11y-speech-rate"));
    return Number.isFinite(v) && v > 0 ? v : 1;
  }, [settings.playbackSpeed]);

  useEffect(() => {
    onStatusChange?.(isRecording ? "processing" : translation ? "ready" : "ready");
  }, [isRecording, translation, onStatusChange]);

  const [rawLandmarks, setRawLandmarks] = useState<Landmark[][] | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  const pipeline = useFastSignPipeline(videoRef, rawLandmarks);

  // Sync isRecording with pipeline
  useEffect(() => {
    if (isRecording) {
      pipeline.beginRecording();
    } else {
      pipeline.commitSegment();
    }
  }, [isRecording]);

  // When pipeline detects a gesture, show particles and update "translation" / confidence
  useEffect(() => {
    if (pipeline.detectedGesture && pipeline.detectedGesture !== "NONE") {
      setTranslation(pipeline.detectedGesture);
      setConfidence(96); // The pipeline commits high-confidence signs automatically
      setShowParticles(true);
      const timer = setTimeout(() => setShowParticles(false), 1500);
      return () => clearTimeout(timer);
    }
  }, [pipeline.detectedGesture]);

  // Sync glossWords updates to history
  useEffect(() => {
    if (pipeline.glossWords.length > 0) {
      const lastWord = pipeline.glossWords[pipeline.glossWords.length - 1];
      onAddToHistory?.(lastWord, lastWord);
    }
  }, [pipeline.glossWords, onAddToHistory]);

  // When pipeline commits a new word, update the display and show particles
  useEffect(() => {
    if (pipeline.glossWords.length > 0) {
      setTranslation(pipeline.glossWords.join(" "));
      setConfidence(96); // The pipeline commits high-confidence signs automatically
      setShowParticles(true);

      // Haptic feedback
      if (settings.hapticFeedback && typeof navigator !== "undefined" && "vibrate" in navigator) {
        try { navigator.vibrate?.([35, 20, 35]); } catch { /* vibration is best-effort */ }
      }

      const timer = setTimeout(() => setShowParticles(false), 1500);
      return () => clearTimeout(timer);
    }
  }, [pipeline.glossWords, settings.hapticFeedback]);

  // Play audio when URL is generated by the pipeline
  useEffect(() => {
    if (pipeline.audioUrl) {
      const audio = new Audio(pipeline.audioUrl);
      audio.onplay = () => setIsPlaying(true);
      audio.onended = () => setIsPlaying(false);
      audio.onerror = () => setIsPlaying(false);
      audio.play().catch(console.error);
    }
  }, [pipeline.audioUrl]);

  const handlePlayClick = () => {
    if (isPlaying) {
      // Cannot easily stop a playing blob audio without ref, but typical phrase is short.
      // Could manage audio object in ref if needed.
      return;
    }
    if (pipeline.glossWords.length > 0) {
      pipeline.triggerTranslate();
    }
  };

  const speakManual = async () => {
    if (!manualText.trim()) return;
    setIsSpeakingManual(true);

    // Try the backend (ElevenLabs) first; null means no backend is reachable.
    const url = await fetchSpeechUrl(manualText.trim());
    if (!url) {
      speakNativeManual();
      return;
    }

    const audio = new Audio(url);
    audio.onplay = () => setIsSpeakingManual(true);
    audio.onended = () => {
      setIsSpeakingManual(false);
      URL.revokeObjectURL(url);
    };
    audio.onerror = () => {
      setIsSpeakingManual(false);
      URL.revokeObjectURL(url);
      speakNativeManual(); // Final fallback inside audio error
    };

    try {
      await audio.play();
    } catch (err) {
      console.warn("Audio playback failed, using native fallback:", err);
      URL.revokeObjectURL(url);
      speakNativeManual();
    }
  };

  const speakNativeManual = () => {
    if (typeof window === "undefined" || !("speechSynthesis" in window)) {
      setIsSpeakingManual(false);
      return;
    }
    try {
      window.speechSynthesis.cancel();
      const u = new SpeechSynthesisUtterance(manualText.trim());
      u.rate = speechRate;
      u.onstart = () => setIsSpeakingManual(true);
      u.onend = () => setIsSpeakingManual(false);
      u.onerror = () => setIsSpeakingManual(false);
      window.speechSynthesis.speak(u);
    } catch {
      setIsSpeakingManual(false);
    }
  };

  const handLandmarks = [
    { x: 48, y: 35 }, { x: 52, y: 22 }, { x: 46, y: 18 }, { x: 42, y: 16 },
    { x: 38, y: 18 }, { x: 56, y: 22 }, { x: 60, y: 16 }, { x: 62, y: 12 },
    { x: 64, y: 9 }, { x: 60, y: 28 }, { x: 65, y: 22 }, { x: 67, y: 17 },
    { x: 69, y: 14 }, { x: 54, y: 34 }, { x: 59, y: 30 }, { x: 62, y: 26 },
    { x: 64, y: 23 }, { x: 48, y: 42 }, { x: 44, y: 38 }, { x: 41, y: 34 },
    { x: 38, y: 30 },
  ];

  return (
    <div className="min-h-screen flex flex-col bg-background overflow-auto">
      {/* Camera slot — fixed height at top, in flow (no overlay) */}
      <div className="relative w-full shrink-0 rounded-b-2xl overflow-hidden border-b border-border" style={{ height: "min(50vh, 320px)" }}>
        {!isRecording && (
          <div className="absolute inset-0 z-0 flex flex-col items-center justify-center gap-2 bg-card/40">
            <div className="w-[50%] max-w-[180px] aspect-[0.7] rounded-2xl border-2 border-dashed border-primary/30 flex items-center justify-center">
              <svg className="w-full h-full opacity-20 p-4" viewBox="0 0 100 100" fill="none">
                <path d="M50 90 C30 90 20 75 20 60 L20 35 C20 30 24 27 28 27 C32 27 36 30 36 35 L36 50 L36 30 C36 25 40 22 44 22 C48 22 52 25 52 30 L52 48 L52 25 C52 20 56 17 60 17 C64 17 68 20 68 25 L68 48 L68 32 C68 27 72 24 76 24 C80 24 84 27 84 32 L84 62 C84 78 70 90 50 90Z" stroke="hsl(var(--primary))" strokeWidth="1.5" strokeLinejoin="round" />
              </svg>
            </div>
            <p className="text-[10px] text-muted-foreground">👍 Yes · ✊ No · ✋ Stop</p>
          </div>
        )}
        {!isRecording && (
          <button
            type="button"
            onClick={() => { setIsRecording(true); setTranslation(""); setConfidence(0); }}
            className="absolute inset-0 z-10 flex flex-col items-center justify-center gap-1 cursor-pointer hover:bg-primary/5 transition-colors"
            aria-label="Start camera"
          >
            <span className="text-sm font-semibold text-primary">Tap to start camera</span>
            <span className="text-xs text-muted-foreground">Show your hand</span>
          </button>
        )}
        {isRecording && (
          <div className="absolute inset-0 z-10 bg-card">
            <HandTracker isActive={true} onLandmarks={setRawLandmarks} />
          </div>
        )}
      </div>

      {/* Top bar - hidden when embedded */}
      {!embedded && (
        <div className={`relative z-10 flex items-center justify-between px-5 pt-12 pb-4 transition-opacity duration-300 ${focusMode ? "a11y-focus-dim" : ""}`}
        >
          <button
            onClick={onBack}
            className="w-9 h-9 rounded-xl bg-secondary border border-border flex items-center justify-center text-muted-foreground hover:text-primary hover:border-primary transition-all duration-200"
          >
            <ArrowLeft size={16} />
          </button>
          <div className="flex items-center gap-2">
            <div className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse" />
            <span className="text-sm font-bold text-primary">AstraSign</span>
          </div>
          <button
            onClick={onSettings}
            className="w-9 h-9 rounded-xl bg-secondary border border-border flex items-center justify-center text-muted-foreground hover:text-primary hover:border-primary transition-all duration-200"
          >
            <Settings size={16} />
          </button>
        </div>
      )}

      {/* Mode label - hidden when embedded */}
      {!embedded && (
        <div className={`relative z-10 flex justify-center mb-2 ${focusMode ? "a11y-focus-dim" : ""}`}>
          <div className="bg-card border border-primary rounded-full px-4 py-1.5 flex items-center gap-2">
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="text-primary">
              <rect x="2" y="1" width="2.5" height="8" rx="1.25" fill="currentColor" />
              <rect x="5.5" y="2.5" width="2.5" height="6.5" rx="1.25" fill="currentColor" opacity="0.8" />
              <rect x="9" y="0.5" width="2.5" height="9" rx="1.25" fill="currentColor" opacity="0.6" />
            </svg>
            <span className="text-xs font-semibold text-primary tracking-wider">SIGN → VOICE</span>
          </div>
        </div>
      )}

      {/* Floating confidence badge - "HELP – 92% Match" style */}
      {translation && (
        <div
          className="fixed top-24 left-1/2 -translate-x-1/2 z-20 px-4 py-2 rounded-xl font-semibold text-sm"
          style={{
            background: "hsl(240 15% 9% / 0.95)",
            border: `1px solid ${confidence >= 90 ? "hsl(142 70% 50% / 0.5)" : confidence >= 70 ? "hsl(40 90% 55% / 0.5)" : "hsl(0 80% 55% / 0.5)"
              }`,
            color: confidence >= 90 ? "hsl(142 70% 50%)" : confidence >= 70 ? "hsl(40 90% 55%)" : "hsl(0 80% 65%)",
            boxShadow: "0 4px 20px rgba(0,0,0,0.3)",
          }}
        >
          {translation.split(" ").slice(0, 2).join(" ").replace(/\.$/, "")} – {confidence}% Accuracy
        </div>
      )}

      {/* Compact strip below camera — in flow, no overlay */}
      <div className="flex flex-col gap-3 px-4 py-3 pb-6 shrink-0">
        {/* Quick phrases — single row */}
        <div className="flex items-center gap-2 overflow-x-auto no-scrollbar">
          <span className="text-[10px] text-muted-foreground uppercase tracking-wider shrink-0">Phrases</span>
          {QUICK_PHRASES.map((p) => (
            <button
              key={p}
              onClick={() => setManualText(p)}
              className="px-2.5 py-1.5 rounded-lg text-[11px] font-medium bg-secondary border border-border text-foreground hover:border-primary shrink-0"
            >
              {p}
            </button>
          ))}
        </div>

        {/* Type message — one line: input + SPEAK */}
        <div className="flex gap-2 items-center">
          <input
            type="text"
            value={manualText}
            onChange={(e) => setManualText(e.target.value)}
            placeholder="Type to speak aloud…"
            className="flex-1 min-w-0 py-2.5 px-3 rounded-xl bg-secondary border border-border text-sm outline-none focus:border-primary"
          />
          <button
            onClick={speakManual}
            disabled={!manualText.trim() || isSpeakingManual}
            className="shrink-0 px-3 py-2.5 rounded-xl bg-primary text-primary-foreground text-xs font-bold flex items-center gap-1.5 disabled:opacity-40"
          >
            <Volume2 size={14} />
            {isSpeakingManual ? "…" : "SPEAK"}
          </button>
        </div>

        {/* Translation result — one line when present */}
        {translation && (
          <div className="px-3 py-2 rounded-xl bg-primary/10 border border-primary/30 flex items-center gap-2">
            <span className="text-xs font-semibold text-primary">{translation}</span>
            <span className="text-[10px] text-muted-foreground ml-auto">{confidence}%</span>
          </div>
        )}

        {/* Record + Accuracy + Play — one compact row */}
        <div className="flex items-center justify-center gap-3 pt-1">
          <div className="w-10 h-10 flex items-center justify-center rounded-full border-2 border-border shrink-0" title="Accuracy">
            <span className="text-[10px] font-bold" style={{ color: confidence >= 90 ? "hsl(142 70% 50%)" : confidence >= 70 ? "hsl(40 90% 55%)" : confidence > 0 ? "hsl(0 80% 55%)" : "hsl(var(--muted-foreground))" }}>
              {confidence ? `${confidence}%` : "—"}
            </span>
          </div>

          <div className="relative flex items-center justify-center p-2">
              {isRecording && (
                <>
                  <div className="absolute inset-0 rounded-full animate-ping opacity-30" style={{ background: "hsl(272 76% 53%)", transform: "scale(1.5)" }} />
                  <div className="absolute inset-0 rounded-full" style={{
                    width: "88px", height: "88px",
                    border: "2px solid hsl(272 76% 53% / 0.4)",
                    borderRadius: "50%",
                    animation: "pulse-purple 1.5s ease-in-out infinite",
                  }} />
                </>
              )}
              <button
                type="button"
                onClick={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  setIsRecording(!isRecording);
                  setTranslation("");
                  setConfidence(0);
                }}
                className="w-16 h-16 min-w-[64px] min-h-[64px] rounded-full flex items-center justify-center transition-transform active:scale-90 relative z-30 cursor-pointer touch-manipulation"
                style={{
                  background: isRecording
                    ? "linear-gradient(135deg, hsl(316 80% 60%), hsl(272 76% 53%))"
                    : "linear-gradient(135deg, hsl(272 76% 53%), hsl(272 76% 40%))",
                  boxShadow: isRecording
                    ? "0 0 30px hsl(316 80% 60% / 0.6), 0 0 60px hsl(316 80% 60% / 0.3)"
                    : "0 0 25px hsl(272 76% 53% / 0.5)",
                }}
                aria-label={isRecording ? "Stop camera" : "Start camera for sign recognition"}
              >
                {isRecording ? (
                  <div className="w-5 h-5 rounded bg-white" />
                ) : (
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                    <rect x="8" y="3" width="8" height="14" rx="4" fill="white" />
                    <path d="M4 12a8 8 0 0016 0" stroke="white" strokeWidth="2" strokeLinecap="round" fill="none" />
                    <line x1="12" y1="20" x2="12" y2="23" stroke="white" strokeWidth="2" strokeLinecap="round" />
                    <line x1="9" y1="23" x2="15" y2="23" stroke="white" strokeWidth="2" strokeLinecap="round" />
                  </svg>
                )}
              </button>
            </div>

          <button
            type="button"
            onClick={handlePlayClick}
            disabled={pipeline.glossWords.length === 0 || pipeline.isTranslating}
            className="w-12 h-12 rounded-xl flex items-center justify-center transition-all disabled:opacity-30 shrink-0"
            style={{
              background: "hsl(183 100% 50% / 0.15)",
              border: "1px solid hsl(183 100% 50% / 0.3)",
              color: "hsl(183 100% 50%)",
            }}
          >
            {pipeline.isTranslating ? (
              <div className="w-5 h-5 border-2 border-current border-t-transparent rounded-full animate-spin" />
            ) : isPlaying ? (
              <Pause size={18} />
            ) : (
              <Play size={18} />
            )}
          </button>
        </div>

        <p className="text-center text-[11px] text-muted-foreground mt-2">
          {isRecording ? pipeline.status : "Tap above or the mic to start"}
        </p>
      </div>
    </div>
  );
}
